services:
  postgres:
    build: ./services/postgres
    container_name: ucas-postgres
    environment:
      POSTGRES_DB: ucas_db
      POSTGRES_USER: ucas_user
      POSTGRES_PASSWORD: ucas_password_123
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: ucas-redis
    command: redis-server --appendonly yes --requirepass ucas_redis_pass
    volumes:
      - ./volumes/redis:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  api-gateway:
    build: ./services/api-gateway
    container_name: ucas-api-gateway
    environment:
      REDIS_HOST: redis
      REDIS_PASSWORD: ucas_redis_pass
    ports:
      - "8000:8000"
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    restart: unless-stopped

  orchestrator:
    build: ./services/orchestrator
    container_name: ucas-orchestrator
    environment:
      - DATABASE_URL=postgresql://ucas_user:ucas_password_123@postgres:5432/ucas_db
    ports:
      - "8001:8001"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  tags-layer:
    build: ./services/tags-layer
    container_name: ucas-tags-layer
    ports:
      - "8010:8010"
    restart: unless-stopped

  xgboost-layer:
    build: ./services/xgboost-layer
    container_name: ucas-xgboost-layer        
    volumes:
      - ./volumes/models:/data/models
    ports:
      - "8020:8020"
    restart: unless-stopped

    # Ollama - LLM Runtime
  ollama:
    image: ollama/ollama:latest
    container_name: ucas-ollama
    volumes:
      - ./volumes/ollama:/root/.ollama
    ports:
      - "11434:11434"
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  # LLM Layer - Classification Service
  llm-layer:
    build: ./services/llm-layer
    container_name: ucas-llm-layer
    depends_on:
      - ollama
    environment:
      - OLLAMA_URL=http://ollama:11434
    ports:
      - "8030:8030"
    restart: unless-stopped

networks:
  default:
    name: ucas_network